kind: pipeline
type: docker
name: Memos Build

trigger:
  branch:
    - main

platform:
  os:
    - windows
    - linux
    - darwin
  arch:
    - amd64
    - arm64

steps:
  - name: Checkout repository
    image: docker
    commands:
      - git clone https://github.com/usememos/memos.git

  - name: Setup Node.js
    image: node:18.12.1
    commands:
      - cd memos/web
      - npm install -g pnpm
      - pnpm i --frozen-lockfile
      - pnpm build
      - mv dist ../server/

  - name: Setup Go
    image: golang:1.19.3
    commands:
      - cd memos
      - go build -o memos-${DRONE_PLATFORM}-${DRONE_ARCH}${DRONE_SYSTEM_EXT} ./main.go

  - name: Upload artifacts
    image: plugins/artifact
    settings:
      target: memos/memos-${DRONE_PLATFORM}-${DRONE_ARCH}${DRONE_SYSTEM_EXT}
