name: Memos Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: List directory contents
      run: ls -R

    - name: Build frontend
      run: |
        if [ -d "web" ]; then
          cd web
        elif [ -d "frontend" ]; then
          cd frontend
        else
          echo "Cannot find web or frontend directory. Skipping frontend build."
          exit 0
        fi
        pnpm install --frozen-lockfile
        pnpm build

    - name: Build backend
      run: |
        if [ -f "go.mod" ]; then
          go mod tidy
          if [ -f "main.go" ]; then
            go build -o memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} ./main.go
          elif [ -f "cmd/memos/main.go" ]; then
            go build -o memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} ./cmd/memos/main.go
          else
            echo "Cannot find main.go"
            exit 1
          fi
        else
          echo "Cannot find go.mod file. Skipping backend build."
          exit 0
        fi

    - name: Prepare artifact
      run: |
        mkdir -p artifact/memos
        if [ -f "memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}" ]; then
          mv memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} artifact/memos/
        fi
        if [ -d "web/dist" ]; then
          mv web/dist artifact/memos/
        elif [ -d "frontend/dist" ]; then
          mv frontend/dist artifact/memos/
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: memos-${{ matrix.goos }}-${{ matrix.goarch }}
        path: artifact/memos

