    - name: Build frontend
      shell: pwsh
      run: |
        if (Test-Path "web") {
          cd web
        } elseif (Test-Path "frontend") {
          cd frontend
        } else {
          Write-Host "Cannot find web or frontend directory. Skipping frontend build."
          exit 0
        }
        pnpm install --frozen-lockfile
        pnpm build

    - name: Build backend
      shell: pwsh
      run: |
        if (Test-Path "go.mod") {
          go mod tidy
          if (Test-Path "main.go") {
            go build -o "memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}" ./main.go
          } elseif (Test-Path "cmd/memos/main.go") {
            go build -o "memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}" ./cmd/memos/main.go
          } else {
            Write-Host "Cannot find main.go"
            exit 1
          }
        } else {
          Write-Host "Cannot find go.mod file. Skipping backend build."
          exit 0
        }

    - name: Prepare artifact
      shell: pwsh
      run: |
        New-Item -Path "artifact/memos" -ItemType Directory -Force
        if (Test-Path "memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}") {
          Move-Item "memos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}" "artifact/memos/"
        }
        if (Test-Path "web/dist") {
          Move-Item "web/dist" "artifact/memos/"
        } elseif (Test-Path "frontend/dist") {
          Move-Item "frontend/dist" "artifact/memos/"
        }
