name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2

    - name: List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "All directories recursively:"
        find . -type d

    - name: Find package.json files
      run: |
        echo "Locating all package.json files:"
        find . -name package.json -type f

    - name: Display package.json contents
      run: |
        echo "Contents of all package.json files:"
        find . -name package.json -type f -print -exec cat {} \;

    - name: Locate and enter web directory
      run: |
        if [ -d "web" ]; then
          echo "Web directory found in root"
          cd web
        elif [ -d "memos/web" ]; then
          echo "Web directory found in memos subfolder"
          cd memos/web
        else
          echo "Web directory not found"
          exit 1
        fi
        echo "Current directory after cd:"
        pwd
        echo "Directory contents:"
        ls -la

    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          echo "Installing dependencies"
          pnpm install --frozen-lockfile
        else
          echo "package.json not found in web directory"
          exit 1
        fi

    - name: Build frontend
      run: |
        if [ -f "package.json" ]; then
          echo "Building frontend"
          pnpm run build
        else
          echo "package.json not found in web directory"
          exit 1
        fi

    - name: Run tests
      run: |
        if [ -f "package.json" ]; then
          echo "Running tests"
          pnpm test
        else
          echo "package.json not found in web directory"
          exit 1
        fi
